# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI+Sample+Application' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI+Sample+Application
  pod 'CashfreePG', '~> 1.1'

end
